services:
    laravel.bolus:
        build:
            context: ./vendor/laravel/sail/runtimes/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.3/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:\
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - postgres
            - redis
    postgres:
        image: 'postgres:14'
        ports:
            - '${FORWARD_DB_PORT:-5434}:5432'
        environment:
            POSTGRES_DB: '${DB_DATABASE:-bolus}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'sail-postgres:/var/lib/postgresql/data'
            - './vendor/laravel/sail/database/postgres/init.sql:/docker-entrypoint-initdb.d/10-init.sql'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
#    ngrok:
#        image: 'ngrok/ngrok:alpine'
#        environment:
#            NGROK_AUTHTOKEN: '${NGROK_AUTHTOKEN}'
#        command: 'http laravel.bolus:80'
#        ports:
#            - '4040:4040'
#        networks:
#            - sail
#        depends_on:
#            - laravel.bolus
networks:
    sail:
        driver: bridge
volumes:
    sail-postgres:
        driver: local
    sail-redis:
        driver: local
